### ISSUE TITLE
[bug] application crashes because of concurrent map read and write

### ISSUE THREAD

**Issue by thielepaul** [mickael-kerjean/filestash#505]
# Description of the bug

From time to time filestash crashes for me with the stacktrace printed below or something similar.
The main reason for this seems to be that at different places in the `server/common` package locks/mutexes are copied, e.g. the `Configuration.Export` function is defined for a value receiver, which leads to a copy of the mutex: https://github.com/mickael-kerjean/filestash/blob/master/server/common/config.go#L352

It should be simple to pass pointers instead of copies for all types that include locks/mutexes. I did this here: https://github.com/thielepaul/filestash/commit/5fc9e50b83541f6aa7ce03c57b2ccf6a2b1dc5c1 and it fixes the concurrent read/write issues for me.

# Step by step instructions to reproduce the bug

The issue is also found by running `go vet` on the code (at least when the lock is directly part of the struct) and it can be reproduced by running `go test -race` with a very simple test file: https://github.com/thielepaul/filestash/blob/5fc9e50b83541f6aa7ce03c57b2ccf6a2b1dc5c1/server/common/config_test.go  

# Can you replicate that error from the demo?

i guess it happens there as well, just check the logs on the demo instance

# Observed behavior

```
fatal error: concurrent map read and map write

goroutine 25329 [running]:
runtime.throw({0x16d217c, 0x20})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc005946760 sp=0xc005946730 pc=0x4f5511
runtime.mapaccess1_faststr(0x16b25ed, 0xc001c6f200, {0x16baac4, 0x13})
        /usr/local/go/src/runtime/map_faststr.go:21 +0x3a5 fp=0xc0059467c8 sp=0xc005946760 pc=0x4d2725
github.com/mickael-kerjean/filestash/server/common.(*KeyValueStore).Get(0xc000384fa8, {0x16baac4, 0xe})
        /build/server/common/cache.go:90 +0xb6 fp=0xc005946828 sp=0xc0059467c8 pc=0x80fd96
github.com/mickael-kerjean/filestash/server/common.(*Configuration).Get(0xc000384f80, {0x16baac4, 0x13}) 
        /build/server/common/config.go:428 +0x99 fp=0xc005946890 sp=0xc005946828 pc=0x814999
github.com/mickael-kerjean/filestash/server/common.Configuration.Export({{0x26815d0, 0x0, 0x0}, {0x0, 0x0}, 0xc0000db080, {0xc000b03cb0, {{0x0, 0x0}, 0x0, ...}}, ...})
        /build/server/common/config.go:372 +0x1d6 fp=0xc005947648 sp=0xc005946890 pc=0x813716
github.com/mickael-kerjean/filestash/server/ctrl.PublicConfigHandler({{0x0, 0x0}, 0x0, 0x0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}}, ...)
        /build/server/ctrl/config.go:65 +0x78 fp=0xc0059476d8 sp=0xc005947648 pc=0x8e5938
github.com/mickael-kerjean/filestash/server/middleware.ApiHeaders.func1({{0x0, 0x0}, 0x0, 0x0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}}, ...)
        /build/server/middleware/http.go:15 +0x1f7 fp=0xc0059477c0 sp=0xc0059476d8 pc=0x8de337
github.com/mickael-kerjean/filestash/server/middleware.NewMiddlewareChain.func1({0x1922ec8, 0xc0002de000}, 0xc000ebe200)
        /build/server/middleware/index.go:22 +0x1d0 fp=0xc005947968 sp=0xc0059477c0 pc=0x8dff50
net/http.HandlerFunc.ServeHTTP(0xc000365d00, {0x1922ec8, 0xc0002de000}, 0x168a800)
        /usr/local/go/src/net/http/server.go:2046 +0x2f fp=0xc005947990 sp=0xc005947968 pc=0x76232f 
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001d2000, {0x1922ec8, 0xc0002de000}, 0xc0027c3300)
        /build/vendor/github.com/gorilla/mux/mux.go:212 +0x202 fp=0xc005947ac0 sp=0xc005947990 pc=0x7a9382
net/http.serverHandler.ServeHTTP({0xc000bc1c50}, {0x1922ec8, 0xc0002de000}, 0xc0027c3300)
        /usr/local/go/src/net/http/server.go:2878 +0x43b fp=0xc005947b80 sp=0xc005947ac0 pc=0x76589b
net/http.(*conn).serve(0xc000018960, {0x1929dc0, 0xc000210180})
        /usr/local/go/src/net/http/server.go:1929 +0xb08 fp=0xc005947fb8 sp=0xc005947b80 pc=0x761408
net/http.(*Server).Serve·dwrap·82()
        /usr/local/go/src/net/http/server.go:3033 +0x2e fp=0xc005947fe0 sp=0xc005947fb8 pc=0x7661ee
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc005947fe8 sp=0xc005947fe0 pc=0x527fe1
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3033 +0x4e8

```

# Expected behavior

filestash should not crash

**Comment by mickael-kerjean** [comment]
thanks for the report, I will need to dig a lot deeper onto that one

**Comment by mickael-kerjean** [comment]
I didn't know about go vet but the commit above did fix those issues

**Comment by mickael-kerjean** [comment]
I'm closing as it seems fix, feel free to comment and I'll reopen
