### ISSUE TITLE
[bug] PHP file don't load if the file has PHP

### ISSUE THREAD

**Issue by crshqd** [mickael-kerjean/filestash#761]
# Description of the bug
Whenever I try to open a PHP file on a FTP server with PHP code in it, it results in a internal error.
```
type:    Error
message: Cannot read properties of undefined (reading 'prev')
trace:   TypeError: Cannot read properties of undefined (reading 'prev')
    at Object.dispatch [as token] (https://demo.filestash.app/assets/363f9bd/lib/vendor/codemirror/mode/php/php.js:187:32)
    at readToken (https://demo.filestash.app/assets/363f9bd/lib/vendor/codemirror/lib/codemirror.js:1183:24)
    at runMode (https://demo.filestash.app/assets/363f9bd/lib/vendor/codemirror/lib/codemirror.js:1240:36)
    at highlightLine (https://demo.filestash.app/assets/363f9bd/lib/vendor/codemirror/lib/codemirror.js:1086:5)
    at getLineStyles (https://demo.filestash.app/assets/363f9bd/lib/vendor/codemirror/lib/codemirror.js:1130:20)
    at buildLineContent (https://demo.filestash.app/assets/363f9bd/lib/vendor/codemirror/lib/codemirror.js:1771:40)
    at getLineContent (https://demo.filestash.app/assets/363f9bd/lib/vendor/codemirror/lib/codemirror.js:2161:12)
    at buildLineElement (https://demo.filestash.app/assets/363f9bd/lib/vendor/codemirror/lib/codemirror.js:2243:17)
    at patchDisplay (https://demo.filestash.app/assets/363f9bd/lib/vendor/codemirror/lib/codemirror.js:4264:20)
    at updateDisplayIfNeeded (https://demo.filestash.app/assets/363f9bd/lib/vendor/codemirror/lib/codemirror.js:4171:5)
```
# Step by step instructions to reproduce the bug

1.  Open a FTP server
2.  Open a PHP file with PHP code

# Can you replicate that error from the demo?
Yes
# Observed behavior
Internal error
# Expected behavior
Regular PHP editor

**Comment by mickael-kerjean** [comment]
Hello, I can't replicate your error on my end:

![screenshot-20241111-041807Z-all](https://github.com/user-attachments/assets/3590f293-52f8-40e3-b6dc-483a5f3fca11)

Can you provide step by step with a sample file I can use to replicate this?

**Comment by crshqd** [comment]
Its fixed, it works
